// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/listar-requisicoes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [
      { type: "text", text: "N\xE3o autenticado. Conecte-se com sua conta do sistema." }
    ],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/listar-requisicoes.ts
var STATUS = [
  "pendente",
  "em_analise",
  "aprovado",
  "cotando",
  "comprado",
  "em_entrega",
  "recebido",
  "rejeitado",
  "cancelado"
];
var listar_requisicoes_default = defineTool({
  name: "listar_requisicoes",
  title: "Listar requisi\xE7\xF5es",
  description: "Lista as requisi\xE7\xF5es de compra vis\xEDveis para o usu\xE1rio conectado, com filtros opcionais por status, prioridade, setor, empresa e texto livre.",
  inputSchema: {
    status: z.enum(STATUS).optional().describe("Filtrar por status da requisi\xE7\xE3o."),
    prioridade: z.enum(["ALTA", "MEDIA", "BAIXA"]).optional().describe("Filtrar por prioridade."),
    setor: z.string().optional().describe("Filtrar pelo setor/departamento do solicitante."),
    empresa: z.string().optional().describe("Filtrar pela empresa do solicitante."),
    busca: z.string().optional().describe("Texto livre buscado no nome do item ou protocolo."),
    limite: z.number().int().optional().describe("Quantidade m\xE1xima de registros (padr\xE3o 20, m\xE1ximo 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, prioridade, setor, empresa, busca, limite }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const max = Math.min(Math.max(limite ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("requisicoes").select(
      "id, protocolo, item_nome, quantidade, unidade, status, prioridade, solicitante_nome, solicitante_setor, solicitante_empresa, fornecedor_nome, valor, valor_orcado, previsao_entrega, created_at"
    ).order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    if (prioridade) query = query.eq("prioridade", prioridade);
    if (setor) query = query.eq("solicitante_setor", setor);
    if (empresa) query = query.eq("solicitante_empresa", empresa);
    if (busca) query = query.or(`item_nome.ilike.%${busca}%,protocolo.ilike.%${busca}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ total: data?.length ?? 0, requisicoes: data ?? [] });
  }
});

// src/lib/mcp/tools/detalhe-requisicao.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var detalhe_requisicao_default = defineTool2({
  name: "detalhe_requisicao",
  title: "Detalhe da requisi\xE7\xE3o",
  description: "Retorna todos os dados de uma requisi\xE7\xE3o espec\xEDfica, buscada pelo protocolo (ex.: REQ-000123) ou pelo ID.",
  inputSchema: {
    protocolo: z2.string().optional().describe("Protocolo da requisi\xE7\xE3o, ex.: REQ-000123."),
    id: z2.string().optional().describe("ID (UUID) da requisi\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ protocolo, id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (!protocolo && !id) return errorResult("Informe o protocolo ou o id da requisi\xE7\xE3o.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("requisicoes").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("protocolo", protocolo);
    const { data, error } = await query.maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Requisi\xE7\xE3o n\xE3o encontrada ou sem permiss\xE3o de acesso.");
    const { data: comentarios } = await supabase.from("comentarios").select("autor_nome, mensagem, created_at").eq("requisicao_id", data.id).order("created_at", { ascending: true });
    return jsonResult({ requisicao: data, comentarios: comentarios ?? [] });
  }
});

// src/lib/mcp/tools/criar-requisicao.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SETORES_HINT = "Setor/departamento do solicitante, ex.: Compras, Endomarketing, TI.";
var criar_requisicao_default = defineTool3({
  name: "criar_requisicao",
  title: "Criar requisi\xE7\xE3o de compra",
  description: "Cria uma nova requisi\xE7\xE3o de compra em nome do usu\xE1rio conectado. O protocolo \xE9 gerado automaticamente pelo sistema.",
  inputSchema: {
    item_nome: z3.string().describe("Nome do item ou servi\xE7o solicitado."),
    quantidade: z3.number().describe("Quantidade solicitada."),
    unidade: z3.string().describe("Unidade de medida, ex.: Unidade, Caixa, Metro."),
    justificativa: z3.string().describe("Justificativa da compra (m\xEDnimo 50 caracteres)."),
    solicitante_nome: z3.string().describe("Nome completo do solicitante."),
    solicitante_email: z3.string().describe("E-mail do solicitante."),
    solicitante_setor: z3.string().describe(SETORES_HINT),
    solicitante_empresa: z3.string().optional().describe("Empresa do solicitante."),
    solicitante_telefone: z3.string().optional().describe("Telefone do solicitante."),
    prioridade: z3.enum(["ALTA", "MEDIA", "BAIXA"]).optional().describe("Prioridade (padr\xE3o MEDIA)."),
    especificacoes: z3.string().optional().describe("Especifica\xE7\xF5es t\xE9cnicas adicionais."),
    centro_custo: z3.string().optional().describe("Centro de custo.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (input.justificativa.trim().length < 50)
      return errorResult("A justificativa deve ter pelo menos 50 caracteres.");
    if (!(input.quantidade > 0)) return errorResult("A quantidade deve ser maior que zero.");
    const { data, error } = await supabaseForUser(ctx).from("requisicoes").insert({
      item_nome: input.item_nome,
      quantidade: input.quantidade,
      unidade: input.unidade,
      justificativa: input.justificativa,
      solicitante_nome: input.solicitante_nome,
      solicitante_email: input.solicitante_email,
      solicitante_setor: input.solicitante_setor,
      solicitante_empresa: input.solicitante_empresa ?? null,
      solicitante_telefone: input.solicitante_telefone ?? null,
      prioridade: input.prioridade ?? "MEDIA",
      especificacoes: input.especificacoes ?? null,
      centro_custo: input.centro_custo ?? null
    }).select("id, protocolo, item_nome, status, prioridade, created_at").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ criada: data });
  }
});

// src/lib/mcp/tools/adicionar-comentario.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var adicionar_comentario_default = defineTool4({
  name: "adicionar_comentario",
  title: "Comentar em uma requisi\xE7\xE3o",
  description: "Adiciona um coment\xE1rio a uma requisi\xE7\xE3o existente, identificada por protocolo ou ID.",
  inputSchema: {
    protocolo: z4.string().optional().describe("Protocolo da requisi\xE7\xE3o, ex.: REQ-000123."),
    id: z4.string().optional().describe("ID (UUID) da requisi\xE7\xE3o."),
    mensagem: z4.string().describe("Texto do coment\xE1rio."),
    autor_nome: z4.string().describe("Nome de quem est\xE1 comentando.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ protocolo, id, mensagem, autor_nome }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    if (!protocolo && !id) return errorResult("Informe o protocolo ou o id da requisi\xE7\xE3o.");
    if (!mensagem.trim()) return errorResult("A mensagem n\xE3o pode ser vazia.");
    const supabase = supabaseForUser(ctx);
    let reqId = id;
    if (!reqId) {
      const { data: data2, error: error2 } = await supabase.from("requisicoes").select("id").eq("protocolo", protocolo).maybeSingle();
      if (error2) return errorResult(error2.message);
      if (!data2) return errorResult("Requisi\xE7\xE3o n\xE3o encontrada ou sem permiss\xE3o de acesso.");
      reqId = data2.id;
    }
    const { data, error } = await supabase.from("comentarios").insert({ requisicao_id: reqId, mensagem, autor_nome }).select("id, mensagem, autor_nome, created_at").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ comentario: data });
  }
});

// src/lib/mcp/tools/resumo-compras.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var resumo_compras_default = defineTool5({
  name: "resumo_compras",
  title: "Resumo de compras",
  description: "Retorna indicadores agregados das requisi\xE7\xF5es vis\xEDveis: contagem por status, valor total comprado, valor or\xE7ado e economia estimada em um per\xEDodo.",
  inputSchema: {
    dias: z5.number().int().optional().describe("Janela em dias a considerar a partir de hoje (padr\xE3o 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ dias }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const janela = Math.min(Math.max(dias ?? 30, 1), 365);
    const desde = new Date(Date.now() - janela * 24 * 60 * 60 * 1e3).toISOString();
    const { data, error } = await supabaseForUser(ctx).from("requisicoes").select("status, valor, valor_orcado, created_at").gte("created_at", desde);
    if (error) return errorResult(error.message);
    const linhas = data ?? [];
    const porStatus = {};
    let totalComprado = 0;
    let totalOrcado = 0;
    for (const r of linhas) {
      porStatus[r.status] = (porStatus[r.status] ?? 0) + 1;
      if (r.valor) totalComprado += Number(r.valor);
      if (r.valor_orcado) totalOrcado += Number(r.valor_orcado);
    }
    return jsonResult({
      periodo_dias: janela,
      total_requisicoes: linhas.length,
      por_status: porStatus,
      valor_total_comprado: totalComprado,
      valor_total_orcado: totalOrcado,
      economia_estimada: totalOrcado - totalComprado,
      moeda: "BRL"
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "hfpcpdzpcmsgjvjxbkls";
var mcp_default = defineMcp({
  name: "requisicoes-compras-mcp",
  title: "Requisi\xE7\xF5es de Compras",
  version: "0.1.0",
  instructions: "Ferramentas do Sistema de Requisi\xE7\xF5es de Compras. Use `listar_requisicoes` para consultar requisi\xE7\xF5es com filtros, `detalhe_requisicao` para ver todos os dados e coment\xE1rios de uma requisi\xE7\xE3o pelo protocolo (REQ-000123), `criar_requisicao` para abrir uma nova solicita\xE7\xE3o, `adicionar_comentario` para comentar e `resumo_compras` para indicadores agregados (status, valores e economia). Todas as ferramentas respeitam as permiss\xF5es do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listar_requisicoes_default, detalhe_requisicao_default, criar_requisicao_default, adicionar_comentario_default, resumo_compras_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
